name: Build EXE file

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository information
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.payload.repository.full_name;
            console.log(`The repository is ${repo}`);

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip binutils
          pip install -U pyinstaller
      
      - name: build py app
        run: python3 pyinstaller.py
      
      - name: list files
        run: ls -a

      - name: Upload titrek-bridge.exe
        uses: actions/upload-artifact@v3
        with:
          name: titrek-bridge.exe
          path: titrek-bridge.exe
