name: Build EXE file

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository information
        uses: actions/github-script@v6
        with:
          script: |
            const repo = context.payload.repository.full_name;
            console.log(`The repository is ${repo}`);

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3 python3-pip binutils
          pip install -U pyinstaller
      
      - name: build py app
        run: python3 pyinstaller.py
      
      - name: list files
        run: ls -a

      - name: Upload titrek-bridge.exe
        uses: actions/upload-artifact@v3
        with:
          name: titrek-bridge.exe
          path: titrek-bridge.exe

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}

      - name: Create Development Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: DEV-${{ github.run_number }}
          release_name: DEV-${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Add titrek-bridge.exe to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: titrek-bridge.exe
          asset_name: titrek-bridge.exe
          asset_content_type: application/octet-stream
